#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("buildpacks-catalog"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: buildpacks-catalog
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: buildpacks-catalog
    kapp.k14s.io/change-rule.buildpacks-catalog: upsert after upserting kpack
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount  
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: buildpacks-catalog.packages.kadras.io
    versionSelection:
      constraints: 0.5.0
      prereleases: {}
  values:
  - secretRef:
      name: buildpacks-catalog-values
---
apiVersion: v1
kind: Secret
metadata:
  name: buildpacks-catalog-values
  namespace: #@ data.values.packages.namespace
stringData:
  values.yaml: #@ yaml.encode(data.values.buildpacks.catalog)

#@ end
