#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("cartographer-supply-chains"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer-supply-chains
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: cartographer-supply-chains
    kapp.k14s.io/change-rule.cartographer: upsert after upserting cartographer
    kapp.k14s.io/change-rule.cartographer-blueprints: upsert after upserting cartographer-blueprints
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cartographer-supply-chains.packages.kadras.io
    versionSelection:
      constraints: 0.5.0
      prereleases: {}
  values:
  - secretRef:
      name: cartographer-supply-chains-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cartographer-supply-chains-values
  namespace: #@ data.values.packages.namespace
stringData:
  values.yaml: #@ yaml.encode(data.values.cartographer.supply_chains)

#@ end
