#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("cartographer-delivery"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer-delivery
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: cartographer-delivery
    kapp.k14s.io/change-rule.cartographer: upsert after upserting cartographer
    kapp.k14s.io/change-rule.cartographer-blueprints: upsert after upserting cartographer-blueprints
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cartographer-delivery.packages.kadras.io
    versionSelection:
      constraints: 0.4.0
      prereleases: {}
  values:
  - secretRef:
      name: cartographer-delivery-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cartographer-delivery-values
  namespace: #@ data.values.packages.namespace
stringData:
  values.yaml: #@ yaml.encode(data.values.cartographer.delivery)

#@ end
