#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("cartographer-delivery") and is_any_profile_enabled([profiles.full]):

#@ def compute_package_values():
#@   values = struct.decode(data.values.cartographer.delivery)
#@
#@   #! Compute values for Git server
#@   if is_any_profile_enabled([profiles.full]):
#@     if data.values.platform.git.server and data.values.platform.git.secret.name and data.values.platform.git.secret.namespace:
#@       if not hasattr(data.values.cartographer.delivery, "git_credentials_secret") or not data.values.cartographer.delivery.git_credentials_secret:
#@         values["git_credentials_secret"] = data.values.platform.git.secret.name
#@       end
#@     end
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer-delivery
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: cartographer-delivery
    kapp.k14s.io/change-rule.cartographer: upsert after upserting cartographer
    kapp.k14s.io/change-rule.cartographer-blueprints: upsert after upserting cartographer-blueprints
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cartographer-delivery.packages.kadras.io
    versionSelection:
      constraints: 0.5.0
      prereleases: {}
  values:
  - secretRef:
      name: cartographer-delivery-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cartographer-delivery-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end
