#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("cert-manager"):

#@ def build_package_values():
#@   values = {}
#@
#@   if data.values.cert_manager.core:
#@     values.update(struct.decode(data.values.cert_manager.core))
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: cert-manager
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cert-manager.packages.kadras.io
    versionSelection:
      constraints: 1.12.1
      prereleases: {}
  values:
    - secretRef:
        name: cert-manager-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(build_package_values())

#@ end