#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("contour"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: contour
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: contour.packages.kadras.io
    versionSelection:
      constraints: 1.24.2
  values:
    - secretRef:
        name: contour-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: #@ data.values.packages.namespace
stringData:
  values.yaml: #@ yaml.encode(data.values.contour)

#@ end