#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("namespace-setup"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: namespace-setup
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: namespace-setup
    kapp.k14s.io/change-rule.cartographer-blueprints: upsert after upserting cartographer-blueprints
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.secretgen-controller: upsert after upserting secretgen-controller
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: namespace-setup.packages.kadras.io
    versionSelection:
      constraints: 0.2.1
  values:
    - secretRef:
        name: namespace-setup-values
---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-setup-values
  namespace: #@ data.values.packages.namespace
stringData:
  values.yaml: #@ yaml.encode(data.values.namespace_setup)

#@ end
