#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kadras-install-admin-cluster-role
  annotations:
    kapp.k14s.io/change-group: serviceaccount
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kadras-install-admin-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kadras-install-admin-cluster-role
subjects:
  - kind: ServiceAccount
    name: kadras-install-sa
    namespace: #@ data.values.packages.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kadras-install-sa
  namespace: #@ data.values.packages.namespace
  annotations:
    kapp.k14s.io/change-group: serviceaccount
