#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_enabled")

#@ if is_package_enabled("secretgen-controller"):

#@ def build_package_values():
#@   values = {}
#@
#@   if data.values.secretgen_controller:
#@     values.update(struct.decode(data.values.secretgen_controller))
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: secretgen-controller
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: secretgen-controller
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: secretgen-controller.packages.kadras.io
    versionSelection:
      constraints: 0.14.8
      prereleases: {}
  values:
  - secretRef:
      name: secretgen-controller-values
---
apiVersion: v1
kind: Secret
metadata:
  name: secretgen-controller-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(build_package_values())

#@ end
