#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("tekton-catalog") and is_any_profile_enabled([profiles.full]):

#@ def compute_package_values():
#@   return data.values.tekton.catalog
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-catalog
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: tekton-catalog
    kapp.k14s.io/change-rule.tekton-pipelines: upsert after upserting tekton-pipelines
    kapp.k14s.io/change-rule.service-account: delete before deleting serviceaccount  
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: tekton-catalog.packages.kadras.io
    versionSelection:
      constraints: 0.2.1
      prereleases: {}
  values:
  - secretRef:
      name: tekton-catalog-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-catalog-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end
