#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("cartographer") and is_any_profile_enabled([profiles.full]):

#@ def compute_package_values():
#@   values = struct.decode(data.values.cartographer.core)
#@
#@   #! Compute values for CA Certificates
#@   if data.values.platform.ca_cert_data:
#@     values["ca_cert_data"] = values["ca_cert_data"] + data.values.platform.ca_cert_data
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cartographer
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: cartographer
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: cartographer.packages.kadras.io
    versionSelection:
      constraints: 0.8.0+kadras.1
      prereleases: {}
  values:
  - secretRef:
      name: cartographer-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cartographer-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end